# CI on Windows via appveyor
# branches:
#   except:
#     - fix-docs

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  # Use the same root miniconda for all builds...
  # The build itself happens in a custom conda environment
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_ENV: "py36-windows"
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_ENV: "py37-windows"
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_ENV: "py38-windows"
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_ENV: "py39-windows"

install:
  # Prepend the Miniconda to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Use the latest conda version
  - "conda update --yes conda"
  # Set up, activate, and list the specific build/test environment
  - "conda env create --file ./ci/requirements-%CONDA_ENV%.yml"
  - "activate test_env"
  - "conda list"
  # Build and install into custom environment
  - "python -m pip install . --no-deps -vv"

build: false

test_script:
  # Run the full test suite
  - "pytest --pyargs climlab.tests --verbose"
