name: test_env
channels:
  - conda-forge
dependencies:
  - pip
  - pooch
  - xarray
  - numpy
  - scipy
  - future
  - pytest
  - codecov
  - pytest-cov
  - climlab-rrtmg
  - climlab-emanuel-convection
  - climlab-cam3-radiation
