name: climlab
dependencies:
    - python
    - numpy
    - scipy
    - netCDF4
    - sphinx
    - matplotlib
    - ipython
    - jupyter
    - sphinx_rtd_theme
    - pip:
        - nbsphinx
        - sphinxcontrib-bibtex
        - numpydoc
