name: climlab-docs
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - matplotlib
  - netCDF4
  - xarray
  - pooch
  - sphinx
  - ipython
  - jupyter
  - future
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib-bibtex
  - numpydoc
  - climlab-rrtmg
  - climlab-cam3-radiation
  - climlab-emanuel-convection
