name: climlab-docs
channels:
  - conda-forge
dependencies:
    - python=3.8
    - numpy
    - pandas
    - scipy
    - matplotlib
    - netCDF4
    - xarray
    - pooch
    - sphinx
    - fortran-compiler
    - toolchain3
    - ipython
    - jupyter
    - future
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-bibtex
    - numpydoc
